name: Publish Docker image
run-name: ${{ github.actor }} pushed an image to dockerhub
on: 
  push:
    branches:
      - main
  pull_request:
jobs:
    Push-fontend-image-to-registry:
        name: Push frontend docker images to registry
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Login into Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
            - name: Extract metadata (tags, labels) for Docker
              id: frontend-metadata
              uses: docker/metadata-action@v5
              with:
                images: vishallokam/three-tier-frontend

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with: 
                context: frontend
                push: ${{ github.event_name != 'pull_request' }}
                tags: vishallokam/three-tier-frontend:latest,vishallokam/three-tier-frontend:1.1
                cache-from: type=gha
                cache-to: type=gha,mode=max


    Push-backend-image-to-registry:
        name: Push backend docker image to registry
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Login into Docker hub
            uses: docker/login-action@v3
            with: 
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}

          - name: Extract metadata for Docker
            id: backend-metadata
            uses: docker/metadata-action@v5
            with:
              images: vishallokam/three-tier-backend

          - name: Build and push docker image
            uses: docker/build-push-action@v5
            with:
              context: backend
              push: ${{ github.event_name != 'pull_request' }}
              tags: vishallokam/three-tier-backend:latest,vishallokam/three-tier-backend:1.1
              cache-from: type=gha
              cache-to: type=gha,mode=max
