name: Publish Docker image
run-name: ${{ github.actor }} pushed an image to dockerhub
on: 
  push:
    branches:
      - main
  pull_request:
jobs:
    Push-fontend-image-to-registry:
        name: Push frontend docker images to registry
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Login into Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
            - name: Extract metadata (tags, labels) for Docker
              id: frontend-metadata
              uses: docker/metadata-action@v5
              with:
                images: vishallokam/three-tier-frontend
                flavor: |
                  latest=false
                tags: |
                  type=raw,value=04
                  type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
                  type=ref,event=pr
                  type=ref,event=branch
                  type=semver,patter={{version}}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with: 
                context: frontend
                push: true
                tags: ${{ steps.frontend-metadata.outputs.tags }}
                labels: ${{ steps.frontend-metadata.outputs.labels
                 }}
                cache-from: type=gha
                cache-to: type=gha,mode=max
                platforms: linux/amd64,linux/arm64,linux/arm/v7


    Push-backend-image-to-registry:
        name: Push backend docker image to registry
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Login into Docker hub
            uses: docker/login-action@v3
            with: 
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}

          - name: Extract metadata for Docker
            id: backend-metadata
            uses: docker/metadata-action@v5
            with:
              images: vishallokam/three-tier-backend
              flavor: |
                lates=false
              tags: |
                type=raw,value=04
                type=raw,value=lates,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
                type=ref,event=pr
                type=ref,event=branch
                type=semver,pattern={{version}}

          - name: Build and push docker image
            uses: docker/build-push-action@v5
            with:
              context: backend
              push: true
              tags: ${{ steps.backend-metadata.outputs.tags }}
              labels: ${{ steps.backend-metadata.outputs.labels }}
              cache-from: type=gha
              cache-to: type=gha,mode=max
              platforms: linux/amd64,linux/arm64,linux/arm/v7
