name: Publish Backend Docker image
run-name: ${{ github.actor }} pushed a backend image to dockerhub
on: 
  push:
    branches:
      - main
  pull_request:
jobs:
    Push-backend-image-to-registry:
        name: Push backend docker image to registry
        runs-on: ubuntu-latest
        permissions:
          pull-requests: write
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Login into Docker hub
            uses: docker/login-action@v3
            with: 
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}

          - name: Extract metadata for Docker
            id: backend-metadata
            uses: docker/metadata-action@v5
            with:
              images: vishallokam/three-tier-backend
              flavor: |
                latest=false
              tags: |
                type=raw,value=04
                type=raw,value=lates,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
                type=ref,event=pr
                type=ref,event=branch
                type=semver,pattern={{version}}

          - name: Build and push docker image
            uses: docker/build-push-action@v5
            with:
              context: backend
              push: true
              tags: ${{ steps.backend-metadata.outputs.tags }}
              labels: ${{ steps.backend-metadata.outputs.labels }}
              cache-from: type=gha
              cache-to: type=gha,mode=max
              platforms: linux/amd64,linux/arm64,linux/arm/v7

          - name: Find comment for image tag
            uses: peter-evans/find-comment@v2
            if: github.event_name == 'pull_request'
            id: bc
            with: 
              issue-number: ${{ github.event.pull_request.number }}
              comment-author: 'github-actions[bot]'
              body-includes: Docker image tag(s) pushed

          - name: Create or update comment for image tag
            uses: peter-evans/create-or-update-comment@v3
            if: github.event_name == 'pull_request'
            with:
              comment-id: ${{ steps.bc.outputs.comment-id }}
              issue-number: $${{ github.event.pull_request.number }}
              body: |
                Docker image tag(s) pushed:
                  ```text
                  ${{ steps.backend-metadata.outputs.tags }}
                  ```
                Labels added to images:
                  ```text
                  ${{ steps.backend-metadata.outputs.labels }}
                  ```
              edit-mode: replace
